const GAME_STAGES = {
  LOBBY: 'LOBBY',
  PROMPT: 'PROMPT',
  RESPONSE: 'RESPONSE',
  ADVISING: 'ADVISING',
  FEEDBACK: 'FEEDBACK',
  SUMMARY: 'SUMMARY',
};

const DEFAULT_ROUNDS = 3;

module.exports = {
  GAME_STAGES, DEFAULT_ROUNDS,
};